In [1]:
import pandas as pd

Series in Pandas

In [2]:
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

CUSTOM INDEX

In [3]:
s = pd.Series([10, 20, 30, 40], index = ["a" ,2, 'c', 'd'])                         # s = pd.Series([10, 20, 30, 40], index = ["a", "b", "c" , "d"])
print(s)
print(s[2])

a    10
2    20
c    30
d    40
dtype: int64
20

SERIES FROM DICTIONARY

In [4]:
data = {"Math": 90, "Physics": 85, "Chemistry": 88}
marks = pd.Series(data)
print(data)
print(marks)

{'Math': 90, 'Physics': 85, 'Chemistry': 88}
Math         90
Physics      85
Chemistry    88
dtype: int64

DATAFRAME IN PANDAS

In [5]:
data = {
    "Name": ["Aman", "Krish", "Karan"],
    "Ages": [22, 23, 21],
    "Marks": [85, 90, 88]
}
print(data)
type(data)

{'Name': ['Aman', 'Krish', 'Karan'], 'Ages': [22, 23, 21], 'Marks': [85, 90, 88]}

dict

In [6]:
marks = pd.DataFrame(data)
print(marks)                    
#Pandas automatically adds default index: This is called a RangeIndex (starts from 0 by default).

    Name  Ages  Marks
0   Aman    22     85
1  Krish    23     90
2  Karan    21     88

In [7]:
#We can also add cutom index in pandas dataframe
marks = pd.DataFrame(
    data,
    index = ["Student1", "Student2", "Student3"]
)
print(marks)

           Name  Ages  Marks
Student1   Aman    22     85
Student2  Krish    23     90
Student3  Karan    21     88

In [8]:
marks.set_index("Name", inplace=True) #if we are setting inplace = true it means we changing the original object itself, if we don't do an another is
print(marks)

       Ages  Marks
Name
Aman     22     85
Krish    23     90
Karan    21     88

In [9]:
df = pd.DataFrame({
    "Name": ["Aman", "Saurav", "Karan", "Shubham", "Abhishek", "Sameer"],
    "Age": [22, 23, 21, 22, 25, 26],
    "Marks": [85, 90, 88, 90, 56, 70]
})
print(df)

       Name  Age  Marks
0      Aman   22     85
1    Saurav   23     90
2     Karan   21     88
3   Shubham   22     90
4  Abhishek   25     56
5    Sameer   26     70

In [10]:
print(df.head())                                                #print the first 5 rows
print(df.tail())                                                #if row are less than or equal to 5 then head and tail will be identical
print(df.head(2))

       Name  Age  Marks
0      Aman   22     85
1    Saurav   23     90
2     Karan   21     88
3   Shubham   22     90
4  Abhishek   25     56
       Name  Age  Marks
1    Saurav   23     90
2     Karan   21     88
3   Shubham   22     90
4  Abhishek   25     56
5    Sameer   26     70
     Name  Age  Marks
0    Aman   22     85
1  Saurav   23     90

In [11]:
df.shape                                            #Number of rows and columns

(6, 3)

In [12]:
df.columns                                         #Show the columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      str
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), str(1)
memory usage: 276.0 bytes

In [14]:
df.describe()                           #for descriptive statistics

             Age      Marks
count   6.000000   6.000000
mean   23.166667  79.833333
std     1.940790  13.891244
min    21.000000  56.000000
25%    22.000000  73.750000
50%    22.500000  86.500000
75%    24.500000  89.500000
max    26.000000  90.000000

SELECTING THE DATA

In [15]:
df["Name"]

0        Aman
1      Saurav
2       Karan
3     Shubham
4    Abhishek
5      Sameer
Name: Name, dtype: str

In [16]:
df[["Name", "Marks"]]

       Name  Marks
0      Aman     85
1    Saurav     90
2     Karan     88
3   Shubham     90
4  Abhishek     56
5    Sameer     70

FILTERING IN PANDAS

In [17]:
df[df["Marks"] > 85]

      Name  Age  Marks
1   Saurav   23     90
2    Karan   21     88
3  Shubham   22     90

In [18]:
#multiple condition

df[(df["Marks"] > 85) & (df["Age"] > 21)]

      Name  Age  Marks
1   Saurav   23     90
3  Shubham   22     90

SORTING + VALUE COUNTS

In [19]:
df.sort_values("Marks", inplace=True)
print(df)

       Name  Age  Marks
4  Abhishek   25     56
5    Sameer   26     70
0      Aman   22     85
2     Karan   21     88
3   Shubham   22     90
1    Saurav   23     90

In [20]:
df.sort_values(["Marks","Age"] , ascending=False, inplace=True)
print(df)

       Name  Age  Marks
1    Saurav   23     90
3   Shubham   22     90
2     Karan   21     88
0      Aman   22     85
5    Sameer   26     70
4  Abhishek   25     56

In [21]:
df["Age"].value_counts()

Age
22    2
23    1
21    1
26    1
25    1
Name: count, dtype: int64

HANDLING MISSING VALUES

In [22]:
#updating the dataset will null values

df = pd.DataFrame({
    "Name": ["Aman", "Saurav", "Karan", "Shubham", None, "Sameer"],
    "Age": [22, 23, None, 22, 25, 26],
    "Marks": [85, None, 88, 90, 56, None]
})
df

      Name   Age  Marks
0     Aman  22.0   85.0
1   Saurav  23.0    NaN
2    Karan   NaN   88.0
3  Shubham  22.0   90.0
4      NaN  25.0   56.0
5   Sameer  26.0    NaN

In [23]:
df.isnull()          #checking the missing values

    Name    Age  Marks
0  False  False  False
1  False  False   True
2  False   True  False
3  False  False  False
4   True  False  False
5  False  False   True

In [24]:
df.isnull().sum()                            #counting the missing values

Name     1
Age      1
Marks    2
dtype: int64

In [25]:
df.dropna()                          #it will drop the whole row which has missing values

      Name   Age  Marks
0     Aman  22.0   85.0
3  Shubham  22.0   90.0

In [26]:
print(df)                            #unless we use inplace = true the dataframe remain the same as it is
cleaned_data = df.dropna()           #so we can create a new dataframe
cleaned_data

      Name   Age  Marks
0     Aman  22.0   85.0
1   Saurav  23.0    NaN
2    Karan   NaN   88.0
3  Shubham  22.0   90.0
4      NaN  25.0   56.0
5   Sameer  26.0    NaN

      Name   Age  Marks
0     Aman  22.0   85.0
3  Shubham  22.0   90.0