In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {
    "Name": ["Aman", "Saurav", "Karan", "Shubham","Abhishek", None, "Sameer"],
    "Age": [22, 23, None, 22, 25, 24, 26],
    "Marks": [85, None, 88, 90, 56, 72, None],
    "Subject" : ["Math", "Physics", "Math", "Chemistry", "Math", "Physics", "Chemistry"]
}
df = pd.DataFrame(data)

In [4]:
print(df.shape)
print(df.dtypes)
print(df.describe().T)

(7, 4)
Name           str
Age        float64
Marks      float64
Subject        str
dtype: object
       count       mean        std   min    25%   50%    75%   max
Age      6.0  23.666667   1.632993  22.0  22.25  23.5  24.75  26.0
Marks    5.0  78.200000  14.254824  56.0  72.00  85.0  88.00  90.0

In [5]:
df[["Name", "Marks"]]

       Name  Marks
0      Aman   85.0
1    Saurav    NaN
2     Karan   88.0
3   Shubham   90.0
4  Abhishek   56.0
5       NaN   72.0
6    Sameer    NaN

### filering - display students with more than 80 marks

In [6]:
df[df["Marks"] > 80]

      Name   Age  Marks    Subject
0     Aman  22.0   85.0       Math
2    Karan   NaN   88.0       Math
3  Shubham  22.0   90.0  Chemistry

#### Complex filtering - display students with more than 80 marks and older than 22 years

In [7]:
df[(df["Marks"] > 80) & (df["Age"] > 22)]

Empty DataFrame
Columns: [Name, Age, Marks, Subject]
Index: []

#### Aggregation - count how many student are enrolled in each subject

In [8]:
df["Subject"].value_counts()

Subject
Math         3
Physics      2
Chemistry    2
Name: count, dtype: int64

#### Sort the dataframe by 'Marks' in descending order

In [9]:
df["Marks"].sort_values(ascending=False)

3    90.0
2    88.0
0    85.0
5    72.0
4    56.0
1     NaN
6     NaN
Name: Marks, dtype: float64

#### Use a specific Pandas function to find the top 2 highest scores (Scholarship Candidates) without sorting the whole dataframe manually

In [10]:
df.nlargest(2, "Marks")

      Name   Age  Marks    Subject
3  Shubham  22.0   90.0  Chemistry
2    Karan   NaN   88.0       Math

#### Identify the student with the lowest marks(Remedial Candidate)

In [11]:
df.loc[df["Marks"].idxmin()]

Name       Abhishek
Age            25.0
Marks          56.0
Subject        Math
Name: 4, dtype: object

### Count the number of null values in each column

In [15]:
df.isna().sum()

Name       1
Age        1
Marks      2
Subject    0
dtype: int64

#### Show the row with null "Marks" values

In [20]:
df[df["Marks"].isna()]

     Name   Age  Marks    Subject
1  Saurav  23.0    NaN    Physics
6  Sameer  26.0    NaN  Chemistry

#### Create a new dataframe called cleaned_df by removing any row that contains null

In [22]:
cleaned_df = df.dropna()
cleaned_df

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math

#### Compare the shape of cleaned_df vs original df

In [23]:
cleaned_df.shape, df.shape

((3, 4), (7, 4))

##### Q. Look at the 'Marks' column in your output. Why are the values floats (eg.85.0) instead of integers?

#### Q. What is the risk of using inplace = True when dropping the missing values?

#### Q. Based on the data, what specific feedback should you give the admin team regarding the "Name" column?