In [5]:
import numpy as np
import pandas as pd

In [6]:
data = {
    "Name": ["Aman", "Sagar", "Shan", "Arip", None, "Anzil", None, "Saneej", "Rafi", "Nick"],
    "Department": ['IT', 'Stock','Stock','IT','Stock', 'IT','HR','HR','HR', 'IT'],
    "Role": ['Dev', 'Quant', 'Quant', 'Cyber', 'Quant', 'Dev', 'Sales', 'Sales', 'Sales', 'Cyber'],
    "Experience": [4, 6, 5, 8, 2, 3, 4, 4, 9, 7],
    "Salary": [40000,100000,100000,35000,80000,40000,40000,55000,60000,35000],
    "Score": [6, 8, 10, 9, 8, 7, 7, 5, 9, 6]
}
df = pd.DataFrame(data)
df

     Name Department   Role  Experience  Salary  Score
0    Aman         IT    Dev           4   40000      6
1   Sagar      Stock  Quant           6  100000      8
2    Shan      Stock  Quant           5  100000     10
3    Arip         IT  Cyber           8   35000      9
4     NaN      Stock  Quant           2   80000      8
5   Anzil         IT    Dev           3   40000      7
6     NaN         HR  Sales           4   40000      7
7  Saneej         HR  Sales           4   55000      5
8    Rafi         HR  Sales           9   60000      9
9    Nick         IT  Cyber           7   35000      6

What is the average salary of each Department?

In [7]:
df.groupby('Department')['Salary'].mean()

Department
HR       51666.666667
IT       37500.000000
Stock    93333.333333
Name: Salary, dtype: float64

What is the average perfomance score for each role?

In [8]:
df.groupby("Role")["Score"].mean()

Role
Cyber    7.500000
Dev      6.500000
Quant    8.666667
Sales    7.000000
Name: Score, dtype: float64

How many actual, non - null perfomance scores entries exist for each department?

In [9]:
df.groupby("Department")["Score"].count()

Department
HR       3
IT       4
Stock    3
Name: Score, dtype: int64

What is the total number of employee recordes(rows) in each department, regardless of whether data is missing?

In [10]:
df["Department"].value_counts()

Department
IT       4
Stock    3
HR       3
Name: count, dtype: int64

Generate a summary table for Salary based on department that show the mean, maximum, minimum, and count in a single line of code.

In [11]:
df.groupby("Department")["Salary"].agg(["mean", "max", "min", "count"])

                    mean     max    min  count
Department
HR          51666.666667   60000  40000      3
IT          37500.000000   40000  35000      4
Stock       93333.333333  100000  80000      3

Generate the same summary table (mean, max, min, count) but analyze the perfomance score based on the role.

In [12]:
df.groupby("Role")["Score"].agg(["mean", "max", "min", "count"])

           mean  max  min  count
Role
Cyber  7.500000    9    6      2
Dev    6.500000    7    6      2
Quant  8.666667   10    8      3
Sales  7.000000    9    5      3

Find the average salary grouped by both department and role.

In [13]:
df.groupby(["Department", "Role"])["Salary"].mean()

Department  Role
HR          Sales    51666.666667
IT          Cyber    35000.000000
            Dev      40000.000000
Stock       Quant    93333.333333
Name: Salary, dtype: float64

Find the average perfomance score grouped by both department and experience level

In [15]:
df.groupby(["Department", "Experience"])["Score"].mean()

Department  Experience
HR          4              6.0
            9              9.0
IT          3              7.0
            4              6.0
            7              6.0
            8              9.0
Stock       2              8.0
            5             10.0
            6              8.0
Name: Score, dtype: float64